### ISSUE TITLE
shallow deep equal?

### ISSUE THREAD

**Issue by laggingreflex** [fengb/chai-generator#2]
How to use with plugins like [shallow-deep-equal](https://github.com/michelsalib/chai-shallow-deep-equal) or [chai-like](https://www.npmjs.com/package/chai-like)?

As I understand, `.yield()` is an end-of-the-chain function, and so are those, so it can't be used right?

Could/should `yield` be an [object flag](http://chaijs.com/guide/plugins/#object-flag) instead?

**Comment by fengb** [comment]
That's a great suggestion. I'll see about adding that today.

**Comment by fengb** [comment]
Sorry for the delay; pushed out the changes as `v2.1.0`. You can now chain off empty .yield and .return (e.g. `.yield().and.like({ foo: "bar" })`
